In [1]:
import numpy as np
import pandas as pd

In [3]:
s1 = pd.Series([10,20,30,40,50])

In [4]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
s1.values

array([10, 20, 30, 40, 50], dtype=int64)

In [8]:
s1.name = 'score'

In [9]:
s1

0    10
1    20
2    30
3    40
4    50
Name: score, dtype: int64

In [10]:
s2 = pd.Series(['a','b','c',1,2,3])

In [11]:
s2

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object

In [12]:
s2.values.dtype

dtype('O')

In [13]:
s2[0]

'a'

In [14]:
s2[4]

2

In [15]:
type(s2[4])

int

In [17]:
type(s2[0])

str

In [18]:
sum(s2[0]+s2[4])

TypeError: can only concatenate str (not "int") to str

In [21]:
s3 = pd.Series([np.nan, 10, 30])

In [22]:
s3

0     NaN
1    10.0
2    30.0
dtype: float64

In [23]:
type(s3[1])

numpy.float64

In [24]:
index_date = ['2021-10-21', '2021-10-22', '2021-10-23','2021-10-24']
s4 = pd.Series([200,150,np.nan,205], index=index_date)

In [25]:
s4

2021-10-21    200.0
2021-10-22    150.0
2021-10-23      NaN
2021-10-24    205.0
dtype: float64

In [26]:
s4.index

Index(['2021-10-21', '2021-10-22', '2021-10-23', '2021-10-24'], dtype='object')

In [27]:
index_date = ['2021-10-21', '2021-10-22', '2021-10-23','2021-10-24']
s4 = pd.Series([200,150,np.nan,205], index=index_date, name='판매량')

In [28]:
s4

2021-10-21    200.0
2021-10-22    150.0
2021-10-23      NaN
2021-10-24    205.0
Name: 판매량, dtype: float64

In [29]:
import datetime

In [31]:
a = pd.Timestamp('2021-10-21')

In [34]:
a.value

1634774400000000000

In [35]:
s5 = pd.Series({'국어': 90, '영어': 95, '수학':85})

In [36]:
s5

국어    90
영어    95
수학    85
dtype: int64

In [37]:
s6 = pd.Series(np.arange(10,100,10))

In [38]:
s6

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int32

In [48]:
a = pd.date_range('2021-10-21', periods=6, freq='D')

In [44]:
a

DatetimeIndex(['2021-10-21 00:00:00', '2021-10-21 19:12:00',
               '2021-10-22 14:24:00', '2021-10-23 09:36:00',
               '2021-10-24 04:48:00', '2021-10-25 00:00:00'],
              dtype='datetime64[ns]', freq=None)

In [49]:
a = pd.date_range('2021-10-21', '2021-10-25', periods=6)

In [50]:
a

DatetimeIndex(['2021-10-21 00:00:00', '2021-10-21 19:12:00',
               '2021-10-22 14:24:00', '2021-10-23 09:36:00',
               '2021-10-24 04:48:00', '2021-10-25 00:00:00'],
              dtype='datetime64[ns]', freq=None)

In [45]:
a = pd.date_range('2021-10-21', periods=6)

In [46]:
a

DatetimeIndex(['2021-10-21', '2021-10-22', '2021-10-23', '2021-10-24',
               '2021-10-25', '2021-10-26'],
              dtype='datetime64[ns]', freq='D')

In [57]:
import datetime
from datetime import date

In [59]:
a1 = date(2021,10,21)

In [60]:
a1

datetime.date(2021, 10, 21)

In [61]:
a1 == a[0]

True

In [62]:
pd.date_range('2021-10-21', '2021-10-27')

DatetimeIndex(['2021-10-21', '2021-10-22', '2021-10-23', '2021-10-24',
               '2021-10-25', '2021-10-26', '2021-10-27'],
              dtype='datetime64[ns]', freq='D')

In [64]:
pd.date_range('2021/10/21', '2021.10.27')

DatetimeIndex(['2021-10-21', '2021-10-22', '2021-10-23', '2021-10-24',
               '2021-10-25', '2021-10-26', '2021-10-27'],
              dtype='datetime64[ns]', freq='D')

In [73]:
pd.date_range('2021/10/21', '10.27.2021')

DatetimeIndex(['2021-10-21', '2021-10-22', '2021-10-23', '2021-10-24',
               '2021-10-25', '2021-10-26', '2021-10-27'],
              dtype='datetime64[ns]', freq='D')

In [76]:
pd.date_range('2021/10/21', '17.10.2021')

DatetimeIndex([], dtype='datetime64[ns]', freq='D')

In [3]:
pd.date_range('2021/10/22', periods=4, freq='W')

DatetimeIndex(['2021-10-24', '2021-10-31', '2021-11-07', '2021-11-14'], dtype='datetime64[ns]', freq='W-SUN')

In [4]:
pd.date_range('2021/10/22', periods=4, freq='W-FRI')

DatetimeIndex(['2021-10-22', '2021-10-29', '2021-11-05', '2021-11-12'], dtype='datetime64[ns]', freq='W-FRI')

In [5]:
pd.date_range('2021/10/22', periods=4, freq='2BM')

DatetimeIndex(['2021-10-29', '2021-12-31', '2022-02-28', '2022-04-29'], dtype='datetime64[ns]', freq='2BM')

In [6]:
pd.date_range('2021/10/22', periods=4, freq='QS')

DatetimeIndex(['2022-01-01', '2022-04-01', '2022-07-01', '2022-10-01'], dtype='datetime64[ns]', freq='QS-JAN')

In [8]:
pd.date_range('2021/10/22 08:00', periods=10, freq='H')

DatetimeIndex(['2021-10-22 08:00:00', '2021-10-22 09:00:00',
               '2021-10-22 10:00:00', '2021-10-22 11:00:00',
               '2021-10-22 12:00:00', '2021-10-22 13:00:00',
               '2021-10-22 14:00:00', '2021-10-22 15:00:00',
               '2021-10-22 16:00:00', '2021-10-22 17:00:00'],
              dtype='datetime64[ns]', freq='H')

In [9]:
pd.date_range('2021/10/22 08:00', periods=10, freq='BH')

DatetimeIndex(['2021-10-22 09:00:00', '2021-10-22 10:00:00',
               '2021-10-22 11:00:00', '2021-10-22 12:00:00',
               '2021-10-22 13:00:00', '2021-10-22 14:00:00',
               '2021-10-22 15:00:00', '2021-10-22 16:00:00',
               '2021-10-25 09:00:00', '2021-10-25 10:00:00'],
              dtype='datetime64[ns]', freq='BH')

In [10]:
pd.date_range('2021/10/22 08:00', periods=10, freq='30T') # == min

DatetimeIndex(['2021-10-22 08:00:00', '2021-10-22 08:30:00',
               '2021-10-22 09:00:00', '2021-10-22 09:30:00',
               '2021-10-22 10:00:00', '2021-10-22 10:30:00',
               '2021-10-22 11:00:00', '2021-10-22 11:30:00',
               '2021-10-22 12:00:00', '2021-10-22 12:30:00'],
              dtype='datetime64[ns]', freq='30T')

In [11]:
pd.date_range('2021/10/22 08:00', periods=10, freq='30min')

DatetimeIndex(['2021-10-22 08:00:00', '2021-10-22 08:30:00',
               '2021-10-22 09:00:00', '2021-10-22 09:30:00',
               '2021-10-22 10:00:00', '2021-10-22 10:30:00',
               '2021-10-22 11:00:00', '2021-10-22 11:30:00',
               '2021-10-22 12:00:00', '2021-10-22 12:30:00'],
              dtype='datetime64[ns]', freq='30T')

In [13]:
pd.date_range('2021/10/22 08:00', periods=10, freq='10S')

DatetimeIndex(['2021-10-22 08:00:00', '2021-10-22 08:00:10',
               '2021-10-22 08:00:20', '2021-10-22 08:00:30',
               '2021-10-22 08:00:40', '2021-10-22 08:00:50',
               '2021-10-22 08:01:00', '2021-10-22 08:01:10',
               '2021-10-22 08:01:20', '2021-10-22 08:01:30'],
              dtype='datetime64[ns]', freq='10S')

In [17]:
index_date = pd.date_range('2021/10/22 08:00', periods=5, freq='D')
s = pd.Series([51, 62, 55, 49, 58], index=index_date)
s

2021-10-22 08:00:00    51
2021-10-23 08:00:00    62
2021-10-24 08:00:00    55
2021-10-25 08:00:00    49
2021-10-26 08:00:00    58
Freq: D, dtype: int64

In [18]:
s.index

DatetimeIndex(['2021-10-22 08:00:00', '2021-10-23 08:00:00',
               '2021-10-24 08:00:00', '2021-10-25 08:00:00',
               '2021-10-26 08:00:00'],
              dtype='datetime64[ns]', freq='D')

In [19]:
s.values

array([51, 62, 55, 49, 58], dtype=int64)

In [21]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [23]:
type(df.values)

numpy.ndarray

In [26]:
df = pd.DataFrame(np.arange(10,100,10).reshape(3,3))
df.values

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [33]:
data = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]])
data = np.arange(1,13).reshape(4,3)
index_date = pd.date_range('2021-10-22', periods=4)
column_list = ['A', 'B', 'C']
df = pd.DataFrame(data, index=index_date, columns=column_list)
df

A   B   C
2021-10-22   1   2   3
2021-10-23   4   5   6
2021-10-24   7   8   9
2021-10-25  10  11  12

In [35]:
table_data = {'연도':[2015, 2016, 2016,2017,2017],
             '지사': ['한국', '한국', '미국','한국','미국'],
             '고객 수': [200, 250, 450, 300, 500]}

In [36]:
table_data

{'연도': [2015, 2016, 2016, 2017, 2017],
 '지사': ['한국', '한국', '미국', '한국', '미국'],
 '고객 수': [200, 250, 450, 300, 500]}

In [40]:
df = pd.DataFrame(table_data, columns=['지사', '연도', '고객 수', '연도','지사'])
df

지사    연도  고객 수    연도  지사
0  한국  2015   200  2015  한국
1  한국  2016   250  2016  한국
2  미국  2016   450  2016  미국
3  한국  2017   300  2017  한국
4  미국  2017   500  2017  미국

In [41]:
df.values

array([['한국', 2015, 200, 2015, '한국'],
       ['한국', 2016, 250, 2016, '한국'],
       ['미국', 2016, 450, 2016, '미국'],
       ['한국', 2017, 300, 2017, '한국'],
       ['미국', 2017, 500, 2017, '미국']], dtype=object)

In [42]:
df.columns

Index(['지사', '연도', '고객 수', '연도', '지사'], dtype='object')

In [43]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
with open('data/coffeeShopSales.txt', 'rt') as f:
    lines = f.readlines()

coffee_menu = lines[0].split()[1:]
lines = lines[1:]

coffee_sales_dict = {}
for menu in coffee_menu:
    coffee_sales_dict[menu] = []

In [53]:
with open('data/coffeeShopSales.txt', 'rt') as f:
    lines = f.readlines()
    
coffee_menu = lines[0].split()[1:]
lines = lines[1:]

coffee_sales_dict = {}
for menu in coffee_menu:
    coffee_sales_dict[menu] = []
    
for line in lines:
    temp = line.split()[1:]

for i in range(len(coffee_menu)):
    coffee_sales_dict[coffee_menu[i]].append(int(temp[i]))

In [54]:
coffee_sales_dict

{'에스프레소': [15], '아메리카노': [49], '카페라테': [38], '카푸치노': [22]}

In [55]:
with open('data/coffeeShopSales.txt', 'rt') as f:
    lines = f.readlines()
    
coffee_menu = lines[0].split()[1:]
lines = lines[1:]

In [58]:
lines


['10.15 10 50 45 20\n',
 '10.16 12 45 41 18\n',
 '10.17 11 53 32 25\n',
 '10.18 15 49 38 22\n']

In [64]:
with open('data/coffeeShopSales.txt', 'rt') as f:
    lines = f.read()
lines

'날짜 에스프레소 아메리카노 카페라테 카푸치노\n10.15 10 50 45 20\n10.16 12 45 41 18\n10.17 11 53 32 25\n10.18 15 49 38 22\n'

In [69]:
data = lines.strip('\n').split('\n')
data

['날짜 에스프레소 아메리카노 카페라테 카푸치노',
 '10.15 10 50 45 20',
 '10.16 12 45 41 18',
 '10.17 11 53 32 25',
 '10.18 15 49 38 22']

In [70]:
data_list = []
for i in data:
    data_list.append(i.split())

In [80]:
arr_data = np.array(data_list)

In [84]:
column_list = arr_data[0,1:]
index_list = arr_data[1:,0]
column_list
index_list

array(['10.15', '10.16', '10.17', '10.18'], dtype='<U5')

In [85]:
df = pd.DataFrame(arr_data[1:,1:], index=index_list, columns = column_list)

In [86]:
df

에스프레소 아메리카노 카페라테 카푸치노
10.15    10    50   45   20
10.16    12    45   41   18
10.17    11    53   32   25
10.18    15    49   38   22

In [88]:
with open('data/coffeeShopSales.txt', 'rt') as f:
    lines = f.read()

data = lines.strip('\n').split('\n')
data_list = []

for i in data:
    data_list.append(i.split())
    
arr_data = np.array(data_list)
column_list = arr_data[0,1:]
index_list = arr_data[1:,0]
index_name = arr_data[0,0]

df = pd.DataFrame(arr_data[1:,1:], index=index_list, columns = column_list)
df.index.name=index_name
df

에스프레소 아메리카노 카페라테 카푸치노
날짜                         
10.15    10    50   45   20
10.16    12    45   41   18
10.17    11    53   32   25
10.18    15    49   38   22

In [89]:
with open('data/coffeeShopSales.txt', 'rt') as f:
    lines = f.readlines()
    
header = lines[0].split()
lines = lines[1:]
index_date = []

In [98]:
with open('data/coffeeShopSales.txt', 'rt') as f:
    lines = f.readlines()
    
header = lines[0].split()
lines = lines[1:]
index_date = []

coffee_sales = []
for line in lines:
    temp = line.split()
    index_date.append(temp[0])
    coffee_sales.append(temp[1:])

coffee_sales = np.array(coffee_sales).astype(np.int32)
coffee_sales

df = pd.DataFrame(coffee_sales, index=index_date, columns=header[1:])
df.index.name = header[0]
df

에스프레소  아메리카노  카페라테  카푸치노
날짜                             
10.15     10     50    45    20
10.16     12     45    41    18
10.17     11     53    32    25
10.18     15     49    38    22

In [107]:
with open('data/coffeeShopSales.txt', 'rt') as f:
    lines = f.readlines()
    
header = lines[0].split()
lines = lines[1:]
index_date = []
coffee_sales = {}

for menu, line in zip(header[1:], lines):
    line = line.split()
    index_date.append(line[0])
    line = [int(val) for val in line[1:]]
    coffee_sales[menu] = line

coffee_sales = pd.DataFrame(coffee_sales, index=index_date)
coffee_sales.index.name = header[0]
df

에스프레소  아메리카노  카페라테  카푸치노
날짜                             
10.15     10     50    45    20
10.16     12     45    41    18
10.17     11     53    32    25
10.18     15     49    38    22

In [108]:
with open('data/coffeeShopSales.txt', 'rt') as f:
    lines = f.readlines()
    
lines

['날짜 에스프레소 아메리카노 카페라테 카푸치노\n',
 '10.15 10 50 45 20\n',
 '10.16 12 45 41 18\n',
 '10.17 11 53 32 25\n',
 '10.18 15 49 38 22\n']

In [114]:
lines[0].strip('\n').split()

['날짜', '에스프레소', '아메리카노', '카페라테', '카푸치노']

In [118]:
aa = pd.read_csv('data/coffeeShopSales.txt', encoding='utf-8')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 0: invalid start byte

In [119]:
s1_a = pd.Series([10,20,30,40,50])
s2_a = pd.Series([1,2,3])
s1_a + s2_a

0    11.0
1    22.0
2    33.0
3     NaN
4     NaN
dtype: float64

In [121]:
s1_b = pd.Series([10,20,30,40,50], index=[1,2,3,4,5])
s2_b = pd.Series([1,2,3], index=[2,3,4])
(s1_b+s2_b).fillna(0)

1     0.0
2    21.0
3    32.0
4    43.0
5     0.0
dtype: float64

In [122]:
df1 = pd.DataFrame({'A':[80,80,80,80,80], 'B':[70,70,70,70,70], 'C':[90,90,90,90,90]})
df1

A   B   C
0  80  70  90
1  80  70  90
2  80  70  90
3  80  70  90
4  80  70  90

In [126]:
df2 = pd.DataFrame({'B':[85,85,85], 'C':[75,75,75], 'D':[95,95,95]}, index=[1,2,3])
df2

B   C   D
1  85  75  95
2  85  75  95
3  85  75  95

In [127]:
df1+df2

A      B      C   D
0 NaN    NaN    NaN NaN
1 NaN  155.0  165.0 NaN
2 NaN  155.0  165.0 NaN
3 NaN  155.0  165.0 NaN
4 NaN    NaN    NaN NaN

In [129]:
df = pd.DataFrame( {'봄': [256.5, 264.3, 215.9, 223.2, 312.8],
              '여름': [770.6, 567.5, 599.8, 387.1, 446.2 ],
              '가을': [363.5, 231.2, 293.1, 247.7, 381.6],
              '겨울': [139.3, 59.9, 76.9, 109.1, 108.1]}, index=[2012,2013,2014,2015,2016])
df

봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1

In [134]:
print(df.sum(), df.mean(), df.var(), df.std(), df.min(), df.max(), sep='\n\n')

봄     1272.7
여름    2771.2
가을    1517.1
겨울     493.3
dtype: float64

봄     254.54
여름    554.24
가을    303.42
겨울     98.66
dtype: float64

봄      1492.143
여름    22167.903
가을     4537.167
겨울      956.388
dtype: float64

봄      38.628267
여름    148.888895
가을     67.358496
겨울     30.925523
dtype: float64

봄     215.9
여름    387.1
가을    231.2
겨울     59.9
dtype: float64

봄     312.8
여름    770.6
가을    381.6
겨울    139.3
dtype: float64


In [135]:
df.cumsum()

봄      여름      가을     겨울
2012   256.5   770.6   363.5  139.3
2013   520.8  1338.1   594.7  199.2
2014   736.7  1937.9   887.8  276.1
2015   959.9  2325.0  1135.5  385.2
2016  1272.7  2771.2  1517.1  493.3

In [142]:
df.describe()

봄          여름          가을          겨울
count    5.000000    5.000000    5.000000    5.000000
mean   254.540000  554.240000  303.420000   98.660000
std     38.628267  148.888895   67.358496   30.925523
min    215.900000  387.100000  231.200000   59.900000
25%    223.200000  446.200000  247.700000   76.900000
50%    256.500000  567.500000  293.100000  108.100000
75%    264.300000  599.800000  363.500000  109.100000
max    312.800000  770.600000  381.600000  139.300000

In [137]:
df.sum(axis=1)

2012    1529.9
2013    1122.9
2014    1185.7
2015     967.1
2016    1248.7
dtype: float64

In [138]:
df.sum(axis=0)

봄     1272.7
여름    2771.2
가을    1517.1
겨울     493.3
dtype: float64

In [139]:
df.count(0)

봄     5
여름    5
가을    5
겨울    5
dtype: int64

In [140]:
df.봄.count()

5

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 2012 to 2016
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   봄       5 non-null      float64
 1   여름      5 non-null      float64
 2   가을      5 non-null      float64
 3   겨울      5 non-null      float64
dtypes: float64(4)
memory usage: 200.0 bytes


In [158]:
df_KTX = pd.DataFrame({'경부선KTX': [39060, 39896, 42005, 43621, 41702, 41266, 32427],
                  '호남선KTX': [7313, 6967, 6873, 6626, 8675, 10622, 9228],
                  '경전선KTX': [3627, 4168, 4088, 4424, 4606, 4984, 5570],
                  '전라선KTX': [309, 1771, 1954, 2244, 3146, 3945, 5766],
                  '동해선KTX': [np.nan,np.nan,np.nan,np.nan,2395, 3786, 6667]}, 
                  index=[2011,2012,2013,2014,2015,2016,2017])
df_KTX.index.name = '연도'

In [159]:
df_KTX

경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX
연도                                          
2011   39060    7313    3627     309     NaN
2012   39896    6967    4168    1771     NaN
2013   42005    6873    4088    1954     NaN
2014   43621    6626    4424    2244     NaN
2015   41702    8675    4606    3146  2395.0
2016   41266   10622    4984    3945  3786.0
2017   32427    9228    5570    5766  6667.0

In [160]:
df_KTX.values  # 모두 실수로 변환됨. nan 때문에.

array([[39060.,  7313.,  3627.,   309.,    nan],
       [39896.,  6967.,  4168.,  1771.,    nan],
       [42005.,  6873.,  4088.,  1954.,    nan],
       [43621.,  6626.,  4424.,  2244.,    nan],
       [41702.,  8675.,  4606.,  3146.,  2395.],
       [41266., 10622.,  4984.,  3945.,  3786.],
       [32427.,  9228.,  5570.,  5766.,  6667.]])

In [161]:
df_KTX['경부선KTX'].values

array([39060, 39896, 42005, 43621, 41702, 41266, 32427], dtype=int64)

In [2]:
index=[2011,2012,2013,2014,2015,2016,2017]

In [3]:
index

[2011, 2012, 2013, 2014, 2015, 2016, 2017]

In [4]:
ss = str(index)

In [5]:
ss

'[2011, 2012, 2013, 2014, 2015, 2016, 2017]'