<a href="https://colab.research.google.com/github/fasthill/AI_advaned_ksa/blob/main/deeplearning/notebooks/chap%2017%20%EC%9E%90%EC%97%B0%EC%96%B4%EC%B2%98%EB%A6%AC-%EC%97%B0%EC%8A%B5%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence, Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.utils import to_categorical

import numpy as np
import tensorflow as tf

In [2]:
text = '해보지 않으면 해낼 수 없다'

In [3]:
result = text_to_word_sequence(text)
print('\n원문:\n',text)
print('\n토큰화:\n',result)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


In [4]:
docs = ['먼저 텍스트의 각 단어를 나누어 토근화 합니다.',
       '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.',
       '토큰화 한 결과는 딥러닝에서 사용할 수 있습니다.',
       ]

In [5]:
token = Tokenizer()  # 토큰화 함수 지정
token.fit_on_texts(docs) # 토큰화 함수에 문장 적용하기

In [6]:
print('\n단어 카운트: \n', token.word_counts)  # 전체 문장에서 사욛된 단어와 사용빈도


단어 카운트: 
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토근화', 1), ('합니다', 1), ('단어로', 1), ('토큰화', 2), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [7]:
print('\n각 단어에 매겨진 인덱스 값:\n', token.word_index) # 가장 먼저 가장 많이 사용된 순서로 토근에 indexing. 각 단어에 0을 제외한 고유번호(index) 부여


각 단어에 매겨진 인덱스 값:
 {'텍스트의': 1, '토큰화': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '토근화': 8, '합니다': 9, '단어로': 10, '해야': 11, '인식됩니다': 12, '한': 13, '결과는': 14, '사용할': 15, '수': 16, '있습니다': 17}


In [8]:
print('\n각 단어가 몇 개의 문장에 포함되어 있는가:\n', token.word_docs) # 몇개의 문장에서 사용되었나?


각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'텍스트의': 2, '토근화': 1, '각': 1, '합니다': 1, '나누어': 1, '단어를': 1, '먼저': 1, '해야': 1, '인식됩니다': 1, '토큰화': 2, '단어로': 1, '딥러닝에서': 2, '있습니다': 1, '수': 1, '사용할': 1, '한': 1, '결과는': 1})


In [9]:
print('\n문장 카운트:', token.document_count) # 몇 개의 문장이 있나?


문장 카운트: 3


In [10]:
doc_seq = token.texts_to_sequences(docs)

In [11]:
doc_seq

[[4, 1, 5, 6, 7, 8, 9], [1, 10, 2, 11, 3, 12], [2, 13, 14, 3, 15, 16, 17]]

In [12]:
to_categorical(doc_seq[0], num_classes=10)

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [13]:
text = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다'

In [14]:
token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [15]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [16]:
word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes=word_size)
print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [17]:
docs = ['너무 재밌네요', '최고예요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다', '한 번 더 보고싶네요',
        '글쎄요', '별로예요','생각보다 지루하네요','연기가 어색해요','재미없어요']

In [18]:
classes = np.array([1,1,1,1,1,0,0,0,0,0])

In [19]:
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고싶네요': 14, '글쎄요': 15, '별로예요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}


In [20]:
x = token.texts_to_sequences(docs)

In [21]:
x

[[1, 2],
 [3],
 [4, 5, 6, 7],
 [8, 9, 10],
 [11, 12, 13, 14],
 [15],
 [16],
 [17, 18],
 [19, 20],
 [21]]

In [22]:
padded_x = pad_sequences(x,4) # padding 작업 적은 것은 0, 긴 것은 잘라버림
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]


In [23]:
word_size = len(token.word_index) + 1 # 0 포함
Embedding(word_size, 8, input_length=4) # input_length: one sentence 길이

In [24]:
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 4, 8)              176       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 8)                 264       
                                                                 
 dense_1 (Dense)             (None, 1)                 9         
                                                                 
Total params: 449
Trainable params: 449
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [27]:
model.fit(padded_x, classes, epochs=20, verbose=1)

Epoch 1/20
1/1 [==============================] - 2s 2s/step - loss: 0.6931 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 21ms/step - loss: 0.6914 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 18ms/step - loss: 0.6898 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 25ms/step - loss: 0.6881 - accuracy: 0.6000
Epoch 5/20
1/1 [==============================] - 0s 13ms/step - loss: 0.6865 - accuracy: 0.7000
Epoch 6/20
1/1 [==============================] - 0s 9ms/step - loss: 0.6849 - accuracy: 0.8000
Epoch 7/20
1/1 [==============================] - 0s 13ms/step - loss: 0.6832 - accuracy: 0.8000
Epoch 8/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6817 - accuracy: 0.8000
Epoch 9/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6801 - accuracy: 0.8000
Epoch 10/20
1/1 [==============================] - 0s 18ms/step - loss: 0.6785 - accuracy: 0.7000
Epoch 11/20
1/1 [===============

In [28]:
print('\n Accuracy: %.4f' %(model.evaluate(padded_x, classes)[1]))

1/1 [==============================] - 0s 342ms/step - loss: 0.6612 - accuracy: 0.9000

 Accuracy: 0.9000


nltk

In [29]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.tokenize import WordPunctTokenizer 
from nltk.tokenize import TreebankWordTokenizer

In [30]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [31]:
print(word_tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))  

['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [32]:
tokenizer = WordPunctTokenizer()
print(tokenizer.tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))

['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', '.', 'Jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [33]:
tokenizer = TreebankWordTokenizer()
print(tokenizer.tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))

['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [34]:
tokenizer = TreebankWordTokenizer()
text = "Starting a home-based restaurant may be an ideal. it doesn't have a food chain or restaurant of their own."
print(tokenizer.tokenize(text))

['Starting', 'a', 'home-based', 'restaurant', 'may', 'be', 'an', 'ideal.', 'it', 'does', "n't", 'have', 'a', 'food', 'chain', 'or', 'restaurant', 'of', 'their', 'own', '.']


In [35]:
token = Tokenizer()
token.fit_on_texts(["Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."])
print(token.word_counts)

OrderedDict([("don't", 1), ('be', 1), ('fooled', 1), ('by', 1), ('the', 1), ('dark', 1), ('sounding', 1), ('name', 1), ('mr', 1), ("jone's", 1), ('orphanage', 1), ('is', 1), ('as', 2), ('cheery', 2), ('goes', 1), ('for', 1), ('a', 1), ('pastry', 1), ('shop', 1)])
