In [17]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence, Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.utils import to_categorical

import numpy as np
import tensorflow as tf

In [2]:
text = '해보지 않으면 해낼 수 없다'

In [6]:
result = text_to_word_sequence(text)
print('\n원문:\n',text)
print('\n토큰화:\n',result)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


In [8]:
docs = ['먼저 텍스트의 각 단어를 나누어 토근화 합니다.',
       '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.',
       '토큰화 한 결과는 딥러닝에서 사용할 수 있습니다.',
       ]

In [9]:
token = Tokenizer()  # 토큰화 함수 지정
token.fit_on_texts(docs) # 토큰화 함수에 문장 적용하기

In [10]:
print('\n단어 카운트: \n', token.word_counts)



단어 카운트: 
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토근화', 1), ('합니다', 1), ('단어로', 1), ('토큰화', 2), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [11]:
print('\n문장 카운트:', token.document_count)
print('\n각 단어가 몇 개의 문장에 포함되어 있는가:\n', token.word_docs)
print('\n각 단어에 매겨진 인덱스 값:\n', token.word_index)


문장 카운트: 3

각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'각': 1, '합니다': 1, '토근화': 1, '단어를': 1, '텍스트의': 2, '나누어': 1, '먼저': 1, '인식됩니다': 1, '단어로': 1, '토큰화': 2, '해야': 1, '딥러닝에서': 2, '수': 1, '결과는': 1, '한': 1, '있습니다': 1, '사용할': 1})

각 단어에 매겨진 인덱스 값:
 {'텍스트의': 1, '토큰화': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '토근화': 8, '합니다': 9, '단어로': 10, '해야': 11, '인식됩니다': 12, '한': 13, '결과는': 14, '사용할': 15, '수': 16, '있습니다': 17}


In [12]:
text = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다'

In [20]:
token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [21]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [23]:
word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes=word_size)
print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [1]:
docs = ['너무 재밌네요', '최고예요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다', '한 번 더 보고싶네요',
        '글쎄요', '별로예요','생각보다 지루하네요','연기가 어색해요','재미없어요']

In [21]:
classes = np.array([1,1,1,1,1,0,0,0,0,0])

In [9]:
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고싶네요': 14, '글쎄요': 15, '별로예요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}


In [10]:
x = token.texts_to_sequences(docs)

In [11]:
x

[[1, 2],
 [3],
 [4, 5, 6, 7],
 [8, 9, 10],
 [11, 12, 13, 14],
 [15],
 [16],
 [17, 18],
 [19, 20],
 [21]]

In [16]:
padded_x = pad_sequences(x,4) # padding 작업 적은 것은 0, 긴 것은 잘라버림
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]


In [18]:
word_size = len(token.word_index) + 1
Embedding(word_size, 8, input_length=4)

In [22]:
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)

Epoch 1/20
1/1 [==============================] - 0s 338ms/step - loss: 0.6882 - accuracy: 0.6000
Epoch 2/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6862 - accuracy: 0.7000
Epoch 3/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6841 - accuracy: 0.7000
Epoch 4/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6821 - accuracy: 0.8000
Epoch 5/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6800 - accuracy: 0.9000
Epoch 6/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6780 - accuracy: 0.9000
Epoch 7/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6759 - accuracy: 0.9000
Epoch 8/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6739 - accuracy: 0.9000
Epoch 9/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6718 - accuracy: 0.9000
Epoch 10/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6697 - accuracy: 0.9000
Epoch 11/20
1/1 [====================

In [26]:
print('\n Accuracy: %.4f' %(model.evaluate(padded_x, classes)[1]))

1/1 [==============================] - 0s 91ms/step - loss: 0.6464 - accuracy: 0.9000

 Accuracy: 0.9000


In [4]:
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [5]:
print(word_tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))  

['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [6]:
from nltk.tokenize import WordPunctTokenizer 

In [7]:
print(WordPunctTokenizer().tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))

['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', '.', 'Jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [8]:
from nltk.tokenize import TreebankWordTokenizer
tokenizer = TreebankWordTokenizer()
text = "Starting a home-based restaurant may be an ideal. it doesn't have a food chain or restaurant of their own."
print(tokenizer.tokenize(text))

['Starting', 'a', 'home-based', 'restaurant', 'may', 'be', 'an', 'ideal.', 'it', 'does', "n't", 'have', 'a', 'food', 'chain', 'or', 'restaurant', 'of', 'their', 'own', '.']
